// Generates compact strategy tables for the browser engine (TypeScript module).

#include "chopsticks.hpp"

#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

using chopsticks::Move;
using chopsticks::MoveType;
using chopsticks::Position;
using chopsticks::Result;
using chopsticks::Rules;
using chopsticks::Solver;

int pack_move(const Move& m) {
    if (m.type == MoveType::ATTACK) {
        return 10 + m.attack.my_hand * 2 + m.attack.their_hand;
    }
    return 100 + static_cast<int>(m.split.new_lo) * 8 + static_cast<int>(m.split.new_hi);
}

int result_code(Result r) {
    switch (r) {
        case Result::LOSS:
            return 0;
        case Result::WIN:
            return 1;
        case Result::DRAW:
            return 2;
        default:
            return -1;
    }
}

void write_variant(std::ostream& out, const std::string& key, const Solver& solver) {
    const Rules& rules = solver.rules();
    const int n = Position::count(rules);
    out << "  " << key << ": [\n";
    for (int i = 0; i < n; ++i) {
        const auto& sol = solver.get_solution(i);
        const int rc = result_code(sol.result);
        if (rc < 0) {
            throw std::runtime_error("Unexpected UNKNOWN result at index " + std::to_string(i));
        }
        out << "    [" << rc << ", " << sol.depth << ", ";
        if (sol.best_moves.empty()) {
            out << "[]";
        } else {
            out << "[";
            for (size_t j = 0; j < sol.best_moves.size(); ++j) {
                if (j != 0) {
                    out << ", ";
                }
                out << pack_move(sol.best_moves[j]);
            }
            out << "]";
        }
        out << "]";
        if (i + 1 < n) {
            out << ",";
        }
        out << "\n";
    }
    out << "  ]";
}

}  // namespace

int main(int argc, char* argv[]) {
    std::string out_path = "web/src/lib/generated/strategy.ts";
    if (argc >= 2) {
        out_path = argv[1];
    }

    std::ofstream out(out_path);
    if (!out) {
        throw std::runtime_error("Cannot open output file: " + out_path);
    }

    out << "// AUTO-GENERATED by export_strategy — do not edit.\n";
    out << "export type StrategyRow = readonly [r: 0 | 1 | 2, d: number, b: readonly number[]];\n";
    out << "export type StrategyTable = readonly StrategyRow[];\n";
    out << "export const STRATEGY_TABLES: {\n";
    out << "  readonly standard: StrategyTable;\n";
    out << "  readonly rollover: StrategyTable;\n";
    out << "  readonly deathAttack: StrategyTable;\n";
    out << "  readonly rolloverDeathAttack: StrategyTable;\n";
    out << "} = {\n";

    Rules r0{5, false, false};
    Solver s0(r0);
    s0.solve();
    write_variant(out, "standard", s0);
    out << ",\n";

    Rules r1{5, true, false};
    Solver s1(r1);
    s1.solve();
    write_variant(out, "rollover", s1);
    out << ",\n";

    Rules r2{5, false, true};
    Solver s2(r2);
    s2.solve();
    write_variant(out, "deathAttack", s2);
    out << ",\n";

    Rules r3{5, true, true};
    Solver s3(r3);
    s3.solve();
    write_variant(out, "rolloverDeathAttack", s3);
    out << "\n} as const;\n";

    out.close();
    return 0;
}
